quarto tags löschen statt mit leerer Zeile ersetzen
Methods-Berlin/RTraining pull request #76
Opened 2023-06-02 18:15 UTC by behnkec

2023-06-05 12:57 UTC, jhorzek requested changes
Ich glaube, das könnte zu Problemen führen, weil wir einen Loop haben, der jedes Element des Vektors x "besucht", wir aber hier innerhalb des Loops die Anzahl an Elementen in x verändern. Hier ein Beispiel, bei dem es zu einem Fehler kommt:

    x <- 1:10
    for(i in 1:length(x)){
      if(x[i] == 5){
        x <- x[-i]
      }
      print(i)
    }

2023-06-08 14:56 UTC, behnkec commented
@jhorzek Vielleicht könnte man den Index aller leeren Zeilen in einem Vektor speichern und diese dann außerhalb der for-Schleife löschen.
Ist das gleiche Problem dann auch bei der Funktion, die die Lösungen entfernt?

2023-06-08 14:58 UTC, jhorzek commented
Ja, das ist eine sehr gute Idee!

2023-06-09 09:10 UTC, jhorzek approved these changes
Super!

2023-06-09 09:11 UTC, merged